version: '3.8'

services:
  react-app:
    # stdin_open: true
    # tty: true
    container_name: react_app_ts_base
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      # - /app/node_modules
      - ./:/app  # Mount the current directory as /app in the container

